### ISSUE TITLE
No backup codes!!!

### ISSUE THREAD

**Issue by mk0xf1e6e** [tonkeeper/tonkeeper-web#248]
Hi, why my backup code is not showing??

![image](https://github.com/user-attachments/assets/2bac9960-22b3-4120-acb9-5bff550047a2)

**Comment by mk0xf1e6e** [comment]
can anyone help ME ??? I have this information about my wallets too,

"auth": {
    "kind": "keychain",
    "keychainStoreKey": xxxxxx
  },
  
I can't send, 

Error =>

index.js:2 00:20:20.592 › TypeError: Cannot read properties of null (reading 'split')
    at b (index.js:5814:42446)
    at async g (index.js:5814:41672)
    at async m (index.js:5814:41463)
    at async Object.mutationFn (index.js:5509:71462)

**Comment by nodesupport1** [comment]
@mk0xf1e6e It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID TON07638
Please see the link below to our dedicated support line:
[Tonkeeper Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by mk0xf1e6e** [comment]
all passwords are stored in the Windows Credentials?? is there any other backups?

**Comment by thangnv98** [comment]
Have you fixed this error yet?

> all passwords are stored in the Windows Credentials?? is there any other backups?
