### ISSUE TITLE
Missing API key

### ISSUE THREAD

**Issue by sebyte** [tonkeeper/tonkeeper-web#89]
Desktop app local build on branch 'main' (958edfdf77):

`
$ tonkeeper --trace-warnings

11:50:11.877 › Application start-up
11:50:11.880 › Reconnect.
11:50:11.895 › Missing connection.
(node:20464) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'split')
    at /usr/lib/tonkeeper/resources/app.asar/.webpack/main/index.js:8:509893
    at Generator.next (<anonymous>)
    at /usr/lib/tonkeeper/resources/app.asar/.webpack/main/index.js:8:508851
    at new Promise (<anonymous>)
    at l (/usr/lib/tonkeeper/resources/app.asar/.webpack/main/index.js:8:508670)
    at E (/usr/lib/tonkeeper/resources/app.asar/.webpack/main/index.js:8:509722)
    at 4575 (/usr/lib/tonkeeper/resources/app.asar/.webpack/main/index.js:8:477217)
    at r (/usr/lib/tonkeeper/resources/app.asar/.webpack/main/index.js:8:646001)
    at /usr/lib/tonkeeper/resources/app.asar/.webpack/main/index.js:8:646553
    at Object.<anonymous> (/usr/lib/tonkeeper/resources/app.asar/.webpack/main/index.js:8:646579)
    at emitUnhandledRejectionWarning (node:internal/process/promises:200:15)
    at processPromiseRejections (node:internal/process/promises:296:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
(node:20464) TypeError: Cannot read properties of undefined (reading 'split')
    at /usr/lib/tonkeeper/resources/app.asar/.webpack/main/index.js:8:509893
    at Generator.next (<anonymous>)
    at /usr/lib/tonkeeper/resources/app.asar/.webpack/main/index.js:8:508851
    at new Promise (<anonymous>)
    at l (/usr/lib/tonkeeper/resources/app.asar/.webpack/main/index.js:8:508670)
    at E (/usr/lib/tonkeeper/resources/app.asar/.webpack/main/index.js:8:509722)
    at 4575 (/usr/lib/tonkeeper/resources/app.asar/.webpack/main/index.js:8:477217)
    at r (/usr/lib/tonkeeper/resources/app.asar/.webpack/main/index.js:8:646001)
    at /usr/lib/tonkeeper/resources/app.asar/.webpack/main/index.js:8:646553
    at Object.<anonymous> (/usr/lib/tonkeeper/resources/app.asar/.webpack/main/index.js:8:646579)
11:50:11.940 › Electron's autoUpdater does not support the 'linux' platform. Ref: https://www.electronjs.org/docs/latest/api/auto-updater#platform-notices
11:50:11.944 › { initArgs: [ '/usr/lib/tonkeeper/Tonkeeper', '--trace-warnings' ] }
11:50:12.187 › UI Start-up
11:50:12.188 › 👋 This message is being logged by "renderer.js", included via webpack
11:50:12.344 › Amplitude Logger [Warn]: Event was dropped by a plugin
11:50:12.532 › Aptabase: Failed to send event TypeError: Failed to fetch
    at file:///usr/lib/tonkeeper/resources/app.asar/.webpack/renderer/main_window/index.js:4441:828
    at Generator.next (<anonymous>)
    at fetch.method (file:///usr/lib/tonkeeper/resources/app.asar/.webpack/renderer/main_window/index.js:4441:756)
    at new Promise (<anonymous>)
    at file:///usr/lib/tonkeeper/resources/app.asar/.webpack/renderer/main_window/index.js:4441:572
    at s (file:///usr/lib/tonkeeper/resources/app.asar/.webpack/renderer/main_window/index.js:4441:767)
    at t.AptabaseElectron.pageView (file:///usr/lib/tonkeeper/resources/app.asar/.webpack/renderer/main_window/index.js:68:9402)
    at file:///usr/lib/tonkeeper/resources/app.asar/.webpack/renderer/main_window/index.js:4182:68340
    at Array.forEach (<anonymous>)
    at i.pageView (file:///usr/lib/tonkeeper/resources/app.asar/.webpack/renderer/main_window/index.js:4182:68326)
11:50:13.345 › Amplitude Logger [Error]: Event rejected due to missing API key
11:50:13.346 › Amplitude Logger [Error]: Event rejected due to missing API key
11:50:13.346 › Amplitude Logger [Error]: Event rejected due to missing API key
11:50:13.347 › Amplitude Logger [Error]: Event rejected due to missing API key
11:50:13.787 › Close connection.
`

**Comment by amakeenk** [comment]
I has the same issue.
